### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by ItIsSeven** [royalfig/the-capitalizer#29]
Would it be possible for you to dockerize this for easy setup/management? 
Would love to see a docker compose file to go with this.

**Comment by royalfig** [comment]
In version 2.0, I'm separating the capitalization logic from the frontend. The capitalization logic will be available as an npm package, so you could use it totally abstracted from the frontend. In this case, I'm not sure whether there'd be much benefit to dockerizing. Let me know if you think otherwise.

**Comment by ItIsSeven** [comment]
Yeah that makes sense, I'm running this on CloudFlare Pages currently, rather than on a Linux Server, so I've had no issues & infact it's easier with the Github integration, being able to just easily add to `lists.js` and the push gets crossed over right away.
